routes/web.php
<?php

use App\Http\Controllers\AlatController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProyekController;
use App\Http\Controllers\RekanController;
use App\Http\Controllers\WebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [WebController::class, 'home'])->name('home');

Auth::routes();

// Auth::routes(['register' => false]);

// Route::get('about', [WebController::class,'about'])->name('about');

// Route::get('contact', [WebController::class,'contact'])->name('contact');

// Route::get('proyek', [WebController::class,'proyek'])->name('proyek');

// Route::get('karyawan', [WebController::class,'karyawan'])->name('karyawan');

Route::prefix('admin')->group(function () {
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('karyawans',KaryawanController::class);
    Route::resource('alats', AlatController::class);
    Route::resource('proyeks', ProyekController::class);
    Route::resource('rekans', RekanController::class);
    Route::resource('profiles', ProfileController::class);
});

resources/views/dashboard.blade.php
@extends('backend.template')
@section('content')


  <!-- page statustic card start -->
  <div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-yellow">{{$jumlahalat}}</h4>
                        <h6 class="text-info m-b-0">Alat</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-box f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-yellow">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0" >Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('alats.create')}}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-green">{{$jumlahkaryawan}}</h4>
                        <h6 class="text-info m-b-0">Karyawan</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-user f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-green">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0">Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('karyawans.create')}}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-blue">{{$jumlahproyek}}</h4>
                        <h6 class="text-info m-b-0">Proyek</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-briefcase f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-blue">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0">Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('alats.create')}}""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-green">{{$jumlahrekan}}</h4>
                        <h6 class="text-info m-b-0">Rekanan</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-users f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-green">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0">Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('rekans.create')}}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- page statustic card end -->
</div>



</div>


@endsection

resources/views/home.blade.php
@extends('backend.template')
@section('content')


  <!-- page statustic card start -->
  <div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-yellow">{{$jumlahalat}}</h4>
                        <h6 class="text-muted m-b-0">Alat</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-box f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-yellow">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0" >Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('alats.create')}}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-green">{{$jumlahkaryawan}}</h4>
                        <h6 class="text-muted m-b-0">Karyawan</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-user f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-green">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0">Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('karyawans.create')}}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-blue">{{$jumlahproyek}}</h4>
                        <h6 class="text-muted m-b-0">Proyek</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-briefcase f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-blue">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0">Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('proyeks.create')}}""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h4 class="text-c-green">{{$jumlahrekan}}</h4>
                        <h6 class="text-muted m-b-0">Rekanan</h6>
                    </div>
                    <div class="col-4 text-right">
                        <i class="feather icon-users f-28"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-c-red">
                <div class="row align-items-center">
                    <div class="col-9">
                        <p class="text-white m-b-0">Add</p>
                    </div>
                    <div class="col-3 text-right">
                        <a class="feather icon-plus text-white f-24" href="{{route('rekans.create')}}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- page statustic card end -->
</div>



</div>


@endsection