routes/web.php
<?php

use App\Http\Controllers\AlatController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProyekController;
use App\Http\Controllers\RekanController;
use App\Http\Controllers\WebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [WebController::class, 'home'])->name('home');

Auth::routes();

// Auth::routes(['register' => false]);

// Route::get('about', [WebController::class,'about'])->name('about');

// Route::get('contact', [WebController::class,'contact'])->name('contact');

// Route::get('proyek', [WebController::class,'proyek'])->name('proyek');

// Route::get('karyawan', [WebController::class,'karyawan'])->name('karyawan');

Route::prefix('admin')->group(function () {
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('karyawans',KaryawanController::class);
    Route::resource('alats', AlatController::class);
    Route::resource('proyeks', ProyekController::class);
    Route::resource('rekans', RekanController::class);
    Route::resource('profiles', ProfileController::class);
});

app/Models/Proyek.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Proyek extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_proyek','pemberi_kerja','deskripsi','tanggal_kontrak','image','tahun'
    ];

    protected $appends = ['text_limit','avatar'];
    public function getTextLimitAttribute(){
        return Str::limit($this->deskripsi,150);
    }
    public function getAvatarAttribute(){
        return url('storage/images/proyek/'.$this->image);
    }
}

app/Http/Controllers/ProyekController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Proyek;

class ProyekController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $proyeks = Proyek::orderBy('id','DESC')->paginate(5);
        return view('proyeks.index',compact('proyeks'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('proyeks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_proyek' => 'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            'pemberi_kerja' => 'required',
            'tanggal_kontrak' => 'required',
            'deskripsi' => 'required',
            'tahun' => 'required',
        ]);

        $proyek = new Proyek;

        $proyek->nama_proyek = $request->nama_proyek;
        $proyek->pemberi_kerja = $request->pemberi_kerja;
        $proyek->tanggal_kontrak = $request->tanggal_kontrak;
        $proyek->deskripsi = $request->deskripsi;
        $proyek->tahun = $request->tahun;
        $proyek->image = go($request->file('image'),'images/proyek')['up'];

        $proyek->save();

        return redirect()->route('proyeks.index')
        ->with('Sukses','Proyek telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Proyek $proyek)
    {
        return view('proyeks.show',compact('proyek'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Proyek $proyek)
    {
        return view('proyeks.edit',compact('proyek'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_proyek' => 'required',
            'deskripsi' => 'required',
            'tanggal_kontrak' => 'required',
            'pemberi_kerja' => 'required',
            'tahun' => 'required',
        ]);

        $proyek = Proyek::find($id);

        if(isset($request->image)){
            $proyek->image = go($request->image,'images/proyek')['up'];
        }

        $proyek->nama_proyek = $request->nama_proyek;
        $proyek->deskripsi = $request->deskripsi;
        $proyek->tanggal_kontrak = $request->tanggal_kontrak;
        $proyek->pemberi_kerja = $request->pemberi_kerja;
        $proyek->tahun = $request->tahun;
        $proyek->save();

        return redirect()->route('proyeks.index')
        ->with('Sukses', 'Proyek telah diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Proyek $proyek)
    {
        $proyek->delete();

        return redirect()->route('proyeks.index')
        ->with('Sukses','Proyek telah dihapus');
    }
}

resources/views/proyeks/create.blade.php
@extends('proyeks.template')

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<div class="row">
    <div class="col-xs-20">
        <div class="card">
            <div class="card-body">
<form action="{{ route('proyeks.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
     <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="nama_proyek">Nama Proyek</span>
                <input type="text" class="form-control" id="nama_proyek" name="nama_proyek" placeholder="Nama Proyek">
            </div>
        </div>
        <hr>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="pemberi_kerja">Pemberi Kerja</span>
                <input type="text" name="pemberi_kerja" class="form-control" id="pemberi_kerja" placeholder="Pemberi Kerja">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="tanggal_kontrak">No dan Tanggal Kontrak</span>
                <input type="text" name="tanggal_kontrak" class="form-control" id="tanggal_kontrak" placeholder="No dan Tanggal Kontrak">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="tahun">Tahun</span>
                <input type="date" name="tahun" class="form-control" id="tahun" placeholder="Tahun">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="deskripsi">Deskripsi Proyek</span>
                <input type="text" name="deskripsi" class="form-control" id="deskripsi" placeholder="Deskripsi Proyek">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="image">Foto Proyek</span>
                <input type="file" name="image" class="form-control" id="image" placeholder="Foto Proyek">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-right">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/proyeks/edit.blade.php
@extends('proyeks.template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('proyeks.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
<form action="{{ route('proyeks.update',$proyek->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="nama_proyek">Nama Proyek</span>
                <input type="text" class="form-control" id="nama_proyek" name="nama_proyek" value="{{$proyek->nama_proyek}}" placeholder="Nama Proyek">
            </div>
        </div>
        <hr>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="pemberi_kerja">Pemberi Kerja</span>
                <input type="text" name="pemberi_kerja" class="form-control" id="pemberi_kerja" value="{{$proyek->pemberi_kerja}}" placeholder="Pemberi Kerja">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="tanggal_kontrak">No dan Tanggal Kontrak</span>
                <input type="text" name="tanggal_kontrak" class="form-control" id="tanggal_kontrak" value="{{$proyek->tanggal_kontrak}}" placeholder="No dan Tanggal Kontrak">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="tahun">Tahun</span>
                <input type="date" name="tahun" class="form-control" id="tahun" value="{{$proyek->tahun}}">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="deskripsi">Deskripsi Proyek</span>
                <input type="text" name="deskripsi" class="form-control" id="deskripsi" value="{{$proyek->deskripsi}}" placeholder="Deskripsi Proyek">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="image">Foto Proyek</span>
                <input type="file" name="image" class="form-control" id="image" placeholder="Foto Proyek">
            </div>
            <div class="form-group">
                <img src="{{$proyek->avatar}}" height="200" width="200" alt="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-right">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>

</form>
@endsection

resources/views/proyeks/index.blade.php
@extends('proyeks.template')

@section('content')



@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

        <div class="col-xs-4">
            <div class="card bg-light">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="text-center">No</th>
                            <th class="text-center">Nama Proyek</th>
                            <th class="text-center">Pemberi Kerja</th>
                            <th class="text-center">No & Tanggal Kontrak</th>
                            <th class="text-center">Tahun</th>
                            <th class="text-center">Deskripsi</th>
                            <th class="text-center">Foto</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    @foreach ($proyeks as $proyek)
                    <tbody>
                        <tr>
                            <td class="text-center">{{ ++$i }}</td>
                            <td class="text-center">{{ Str::limit($proyek->nama_proyek, 5) }}</td>
                            <td class="text-center">{{ $proyek->pemberi_kerja }}</td>
                            <td class="text-center">{{ Str::limit($proyek->tanggal_kontrak, 5) }}</td>
                            <td class="text-center">{{ $proyek->tahun}}</td>
                            <td class="text-center">{{ Str::limit($proyek->deskripsi, 5) }}</td>
                            <td class="text-center"><img src="{{$proyek->avatar}}" height="75" width="75" alt=""></td>
                            <td class="text-center">
                                <form action="{{ route('proyeks.destroy',$proyek->id) }}" method="POST">

                                    <a class="btn btn-info btn-sm" href="{{ route('proyeks.show',$proyek->id) }}">Show</a>

                                    <a class="btn btn-primary btn-sm" href="{{ route('proyeks.edit',$proyek->id) }}">Edit</a>

                                    @csrf
                                    @method('DELETE')

                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>

                                </form>
                            </td>
                        </tr>
                    </tbody>
                    @endforeach
                </table>
            </div>
        </div>
        <div class="float-right">
            <a class="btn btn-success" href="{{ route('proyeks.create') }}">Tambah Proyek</a>
        </div>
        {{$proyeks->links('vendor.pagination.bootstrap-4')}}


@endsection

resources/views/proyeks/show.blade.php
@extends('proyeks.template')

@section('content')

<div class="col-xs-4">
    <div class="card bg-light">
        <center>
        <div class="card-header"><h1>Data Proyek</h1></div>
        <div class="card-body">
            <strong>Nama Proyek :</strong>
            <h3 class="card-title text-black text-danger">{{ $proyek->nama_proyek }}</h3>
            <strong>Pemberi Kerja :</strong>
            <h3 class="card-title text-black text-danger">{{ $proyek->pemberi_kerja }}</h3>
            <strong>No & Tanggal Kontrak :</strong>
            <h3 class="card-title text-black text-danger">{{ $proyek->tanggal_kontrak }}</h3>
            <strong>Tahun :</strong>
            <h3 class="card-title text-black text-danger">{{ $proyek->tahun }}</h3>
            <strong>Deskripsi Proyek :</strong>
            <h3 class="card-title text-black text-danger">{{ $proyek->deskripsi }}</h3>
            <strong>Foto Proyek :</strong><br>
            <img src="{{$proyek->avatar}}" height="200" width="200" alt="">
        </div>
    </div>
</center>
<a class="btn btn-secondary" href="{{ route('proyeks.index') }}"> Back</a>
</div>
@endsection

resources/views/proyeks/template.blade.php
@extends('backend.template')

@section('content')


<!DOCTYPE html>
<html>
<head>
    <title>PT GRAHA KREASINDO UTAMA</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>

@endsection