routes/web.php
<?php

use App\Http\Controllers\AlatController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProyekController;
use App\Http\Controllers\RekanController;
use App\Http\Controllers\WebController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [WebController::class, 'home'])->name('home');

Auth::routes();

// Auth::routes(['register' => false]);

// Route::get('about', [WebController::class,'about'])->name('about');

// Route::get('contact', [WebController::class,'contact'])->name('contact');

// Route::get('proyek', [WebController::class,'proyek'])->name('proyek');

// Route::get('karyawan', [WebController::class,'karyawan'])->name('karyawan');

Route::prefix('admin')->group(function () {
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('karyawans',KaryawanController::class);
    Route::resource('alats', AlatController::class);
    Route::resource('proyeks', ProyekController::class);
    Route::resource('rekans', RekanController::class);
    Route::resource('profiles', ProfileController::class);
});

app/Models/Rekan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Rekan extends Model
{
    use HasFactory;
    protected $fillable = [
        'nama','alamat','image'
    ];
    protected $appends = ['avatar'];
    public function getAvatarAttribute(){
        return url('storage/images/rekan/'.$this->image);
    }

}

app/Http/Controllers/RekanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Rekan;
use Illuminate\Http\Request;

class RekanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rekans = Rekan::orderBy('id','DESC')->paginate(5);
        // return $rekans;
        return view('rekans.index',compact('rekans'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('rekans.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            'alamat' => 'required',
        ]);



        $rekan = new Rekan;

        $rekan->nama = $request->nama;
        $rekan->alamat = $request->alamat;
        $rekan->image = go($request->file('image'),'images/rekan')['up'];

        $rekan->save();

        return redirect()->route('rekans.index')
        ->with('Sukses','Rekan telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Rekan $rekan)
    {
        return view('rekans.show',compact('rekan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Rekan $rekan)
    {
        return view('rekans.edit',compact('rekan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama'=>'required',
            'alamat'=>'required',
        ]);

        $rekan = Rekan::find($id);

        if(isset($request->image)){
            $rekan->image = go($request->image,'images/rekan')['up'];
        }

        $rekan->nama = $request->nama;
        $rekan->alamat = $request->alamat;
        $rekan->save();

        return redirect()->route('rekans.index')
        ->with('Sukses', 'Rekan telah diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Rekan $rekan)
    {
        $rekan->delete();

        return redirect()->route('rekans.index')
        ->with('Sukses','Rekan telah dihapus');
    }
}

resources/views/rekans/create.blade.php
@extends('rekans.template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('rekans.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
<form action="{{ route('rekans.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
     <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="nama">Nama Rekanan</span>
                <input type="text" class="form-control" id="nama" name="nama" placeholder="Nama Rekanan">
            </div>
        </div>
        <hr>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="alamat">Alamat</span>
                <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="image">Logo</span>
                <input type="file" name="image" class="form-control" id="image" placeholder="Logo">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-right">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/rekans/edit.blade.php
@extends('rekans.template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('proyeks.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
<form action="{{ route('rekans.update',$rekan->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="nama">Nama Rekan</span>
                <input type="text" class="form-control" id="nama" name="nama" value="{{$rekan->nama}}" placeholder="Nama Rekan">
            </div>
        </div>
        <hr>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="alamat">Alamat</span>
                <input type="text" name="alamat" class="form-control" id="alamat" value="{{$rekan->alamat}}" placeholder="Alamat">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <span class="floating-label" for="image">Logo</span>
                <input type="file" name="image" class="form-control" id="image" placeholder="Logo" >
            </div>
            <div class="form-group">
                <img src="{{$rekan->avatar}}" height="200" width="200" alt="" name="image">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-right">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>

</form>
@endsection

resources/views/rekans/index.blade.php
@extends('rekans.template')

@section('content')



@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

        <div class="col-xs-4">
            <div class="card bg-light">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="text-center">No</th>
                            <th class="text-center">Nama Rekan</th>
                            <th class="text-center">Alamat</th>
                            <th class="text-center">Logo</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    @foreach ($rekans as $rekan)
                    <tbody>
                        <tr>
                            <td class="text-center">{{ ++$i }}</td>
                            <td class="text-center">{{ $rekan->nama }}</td>
                            <td class="text-center">{{ $rekan->alamat }}</td>
                            <td class="text-center"><img src="{{$rekan->avatar}}" height="75" width="75" alt=""></td>
                            <td class="text-center">
                                <form action="{{ route('rekans.destroy',$rekan->id) }}" method="POST">

                                    <a class="btn btn-info btn-sm" href="{{ route('rekans.show',$rekan->id) }}">Show</a>

                                    <a class="btn btn-primary btn-sm" href="{{ route('rekans.edit',$rekan->id) }}">Edit</a>

                                    @csrf
                                    @method('DELETE')

                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>

                                </form>
                            </td>
                        </tr>
                    </tbody>
                    @endforeach
                </table>
            </div>
        </div>
        <div class="float-right">
            <a class="btn btn-success" href="{{ route('rekans.create') }}">Tambah Rekanan</a>
        </div>
        {{$rekans->links('vendor.pagination.bootstrap-4')}}


@endsection

resources/views/rekans/show.blade.php
@extends('rekans.template')

@section('content')

<div class="col-xs-4">
    <div class="card bg-light">
        <center>
        <div class="card-header"><h1>Data Rekanan</h1></div>
        <div class="card-body">
            <strong>Nama Rekan :</strong>
            <h3 class="card-title text-black text-danger">{{ $rekan->nama }}</h3>
            <strong>Alamat :</strong>
            <h3 class="card-title text-black text-danger">{{ $rekan->alamat }}</h3>
            <strong>Logo :</strong><br>
            <img src="{{$rekan->avatar}}" height="200" width="200" alt="">
        </div>
    </div>
</center>
<a class="btn btn-secondary" href="{{ route('rekans.index') }}"> Back</a>
</div>
@endsection

resources/views/rekans/template.blade.php
@extends('backend.template')

@section('content')


<!DOCTYPE html>
<html>
<head>
    <title>PT GRAHA KREASINDO UTAMA</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>

@endsection